//Ingreso de informacion basica
let nombre_completo=""; 
let edad="0";
let tipo_Documento="";
let nuemro_Documento="";

//Validacion de perfil
let salario="0";
let comisiones="0";
let total_horas="0";
let nivel_riesgo="0";

//Valores y tarifas Colombia 2026
const salario_minimo_legal="1750905";
const salario_minimo_integral="22761765";
const subsidio_transporte="249095";
const valor_tributario="5237";

//calculo de obligaciones laborales
let ingeresobase_cotizacion ="";