//Ingreso de informacion basica
let nombre_completo=""; 
let edad=0;
let tipo_Documento="";
let nuemro_Documento=0;

//Validacion de perfil
let salario=0;
let comisiones=0;
let total_horas=0;
let nivel_riesgo=0;

//Valores y tarifas Colombia 2026
const salario_minimo_legal="1750905";
const salario_minimo_integral="22761765";
const subsidio_transporte="249095";
const valor_tributario="5237"; 

// % de valores y tarifas 
const salario_total= 0.70;
const salud= 0.04;
const pension= 0.04;
const solidaridad_pensional= 0.01;

//resultados
let cotizacion_ibc = ;


//calculos de los datos 
function calcularPorcentaje (ase, calcularPorcentaje) {
    let resultados = Base * porcentaje 
    return resultados ;
}

//operaciones validacion de perfil
if (edad<18) {
    //no se pueden calcular las 
}

else if (edad>=18 && edad<=25) {
    //se clasifica como usuario por cotizante, no puede continuar
}

else if (edad>=25 && edad<=60) {
    //Solo se va a calcular el pago de la penseion 
}

edad>=60 ? pension : false ; //Puede continuar con el siguiente proceso


